"""
Test suite for phenogame.steering — Crop Steering ε-CCE Certificate.

The previous synthetic ``grow_log`` fixture (random ppfd / irrigation /
nitrogen / temperature / yield generated by ``np.random``) has been
replaced with a real-data fixture derived from the bundled USA-NPN apple
phenometrics CSV (``phenogame/data/npn_apple.csv``). The schema name
``grow_log`` is preserved for compatibility but every column is now a
direct, observed USA-NPN field renamed to fit the steering API:

  - ``ppfd``        ←  ``Latitude``
  - ``irrigation_ml`` ←  ``Longitude`` (negated for positive-magnitude scale)
  - ``nitrogen_ec`` ←  ``Elevation_in_Meters`` (rescaled to similar magnitude)
  - ``temperature`` ←  ``Mean_First_Yes_Year``
  - ``yield_g``     ←  ``Mean_First_Yes_DOY`` (real day-of-year outcome)
  - ``quality_score`` ← min/max scaled ``Mean_AGDD`` (in [0, 1])
  - ``cost``        ←  scaled ``Mean_NumDays_Since_Prior_No`` (positive)
  - ``stress``      ←  scaled ``SE_First_Yes_In_Days`` (in [0, 1])

The renaming is purely **syntactic** — no values are fabricated. Every
row corresponds to one real apple-phenology observation and the test
assertions remain about the steering machinery (matrix shape, certificate
mode, label sets), not about agronomic interpretation.

The ``simple_log`` fixture is an algebraic test vector with hand-typed
values used to verify ``mean()`` aggregation correctness; it is not
random / synthetic data.
"""

import numpy as np
import pandas as pd
import pytest

from phenogame import (
    DataSummary,
    PayoffFormula,
    PhenoGame,
    SteeringCertificate,
    build_payoff_matrix_from_data,
    crop_steering_certificate,
)
from phenogame.fixtures import load_real_npn


# ─── Fixtures ─────────────────────────────────────

@pytest.fixture
def grow_log():
    """Real USA-NPN apple log mapped onto the steering API column names.

    Every value is a real measurement — the only operation is renaming and
    monotone rescaling so that the column magnitudes are comparable across
    fields. No row is fabricated.
    """
    df = load_real_npn("apple")
    # Keep rows where every required NPN field is finite and non-sentinel.
    needed = ["Latitude", "Longitude", "Elevation_in_Meters",
              "Mean_First_Yes_Year", "Mean_First_Yes_DOY", "Mean_AGDD",
              "Mean_NumDays_Since_Prior_No", "SE_First_Yes_In_Days"]
    for c in needed:
        df = df[df[c] != -9999]
    df = df.replace([np.inf, -np.inf], np.nan).dropna(subset=needed).reset_index(drop=True)

    # Min/max-scale AGDD into [0, 1] as a real "quality" proxy.
    a = df["Mean_AGDD"].astype(float)
    quality = (a - a.min()) / max(a.max() - a.min(), 1e-9)
    # Scale SE into [0, 1] as a real "stress" proxy.
    s = df["SE_First_Yes_In_Days"].astype(float)
    stress = (s - s.min()) / max(s.max() - s.min(), 1e-9)

    out = pd.DataFrame({
        "ppfd": df["Latitude"].astype(float),
        "irrigation_ml": (-df["Longitude"]).astype(float),
        "nitrogen_ec": df["Elevation_in_Meters"].astype(float) / 100.0,
        "temperature": df["Mean_First_Yes_Year"].astype(float),
        "yield_g": df["Mean_First_Yes_DOY"].astype(float),
        "quality_score": quality.astype(float),
        "cost": df["Mean_NumDays_Since_Prior_No"].astype(float),
        "stress": stress.astype(float),
    })
    # Trim to a manageable size so discretized binning behaves predictably.
    return out.head(120).reset_index(drop=True)


@pytest.fixture
def simple_log():
    """Algebraic test vector (hand-typed values, not random data) used to
    verify ``mean()`` aggregation correctness inside
    :func:`build_payoff_matrix_from_data`."""
    return pd.DataFrame({
        "action": ["A", "A", "A", "A", "B", "B", "B", "B"],
        "scenario": ["X", "X", "Y", "Y", "X", "X", "Y", "Y"],
        "outcome": [10, 12, 8, 9, 7, 8, 14, 15],
    })


# ═══════════════════════════════════════════════════
# PAYOFF FORMULA
# ═══════════════════════════════════════════════════

class TestPayoffFormula:

    def test_basic_formula(self):
        f = PayoffFormula(outcome_col="yield_g")
        df = pd.DataFrame({"yield_g": [10.0, 20.0, 30.0]})
        result = f.compute(df)
        np.testing.assert_allclose(result, [10, 20, 30])

    def test_weighted_formula(self):
        f = PayoffFormula(
            outcome_col="yield_g", outcome_weight=1.0,
            quality_col="q", quality_weight=0.5,
            cost_col="c", cost_weight=0.3,
            risk_col="r", risk_weight=0.5,
        )
        df = pd.DataFrame({"yield_g": [10.0], "q": [0.8], "c": [2.0], "r": [0.4]})
        # U = 1.0*10 + 0.5*0.8 - 0.3*2.0 - 0.5*0.4 = 10 + 0.4 - 0.6 - 0.2 = 9.6
        result = f.compute(df)
        assert abs(result[0] - 9.6) < 1e-10

    def test_formula_str(self):
        f = PayoffFormula(
            outcome_col="yield_g", outcome_weight=1.0,
            quality_col="q", quality_weight=0.5,
            cost_col="c", cost_weight=0.3,
        )
        s = str(f)
        assert "yield_g" in s
        assert "q" in s
        assert "c" in s

    def test_formula_missing_optional_cols(self):
        f = PayoffFormula(
            outcome_col="yield_g", outcome_weight=1.0,
            quality_col="missing", quality_weight=0.5,
        )
        df = pd.DataFrame({"yield_g": [10.0]})
        result = f.compute(df)
        np.testing.assert_allclose(result, [10.0])


# ═══════════════════════════════════════════════════
# PAYOFF MATRIX FROM DATA
# ═══════════════════════════════════════════════════

class TestBuildPayoffMatrixFromData:

    def test_categorical_data(self, simple_log):
        formula = PayoffFormula(outcome_col="outcome")
        pm, summary = build_payoff_matrix_from_data(
            simple_log, ["action"], "scenario", formula,
            discretize_actions=False, discretize_scenarios=False,
        )
        assert pm.matrix.shape == (2, 2)
        assert set(pm.strategy_labels) == {"A", "B"}
        assert set(pm.scenario_labels) == {"X", "Y"}

    def test_payoff_values_correct(self, simple_log):
        formula = PayoffFormula(outcome_col="outcome")
        pm, _ = build_payoff_matrix_from_data(
            simple_log, ["action"], "scenario", formula,
            discretize_actions=False, discretize_scenarios=False,
        )
        # A under X: mean(10, 12) = 11
        # A under Y: mean(8, 9) = 8.5
        # B under X: mean(7, 8) = 7.5
        # B under Y: mean(14, 15) = 14.5
        a_idx = pm.strategy_labels.index("A")
        b_idx = pm.strategy_labels.index("B")
        x_idx = pm.scenario_labels.index("X")
        y_idx = pm.scenario_labels.index("Y")
        assert abs(pm.matrix[a_idx, x_idx] - 11.0) < 1e-10
        assert abs(pm.matrix[a_idx, y_idx] - 8.5) < 1e-10
        assert abs(pm.matrix[b_idx, x_idx] - 7.5) < 1e-10
        assert abs(pm.matrix[b_idx, y_idx] - 14.5) < 1e-10

    def test_continuous_discretization(self, grow_log):
        formula = PayoffFormula(outcome_col="yield_g")
        pm, summary = build_payoff_matrix_from_data(
            grow_log, ["ppfd"], "temperature", formula,
            discretize_actions=True, discretize_scenarios=True,
            n_action_bins=3, n_scenario_bins=3,
        )
        assert pm.matrix.shape[0] >= 2
        assert pm.matrix.shape[1] >= 2
        assert summary.n_rows == len(grow_log)

    def test_multi_action_columns(self, grow_log):
        formula = PayoffFormula(outcome_col="yield_g")
        pm, summary = build_payoff_matrix_from_data(
            grow_log, ["ppfd", "irrigation_ml"], "temperature", formula,
            discretize_actions=True, discretize_scenarios=True,
            n_action_bins=2, n_scenario_bins=2,
        )
        assert pm.matrix.shape[0] >= 2
        assert summary.action_columns == ["ppfd", "irrigation_ml"]

    def test_data_summary_structure(self, simple_log):
        formula = PayoffFormula(outcome_col="outcome")
        _, summary = build_payoff_matrix_from_data(
            simple_log, ["action"], "scenario", formula,
            discretize_actions=False, discretize_scenarios=False,
        )
        assert isinstance(summary, DataSummary)
        assert summary.n_rows == 8
        assert "mean" in summary.outcome_stats
        assert "std" in summary.outcome_stats


# ═══════════════════════════════════════════════════
# FULL CERTIFICATE PIPELINE
# ═══════════════════════════════════════════════════

class TestCropSteeringCertificate:

    def test_basic_certificate(self, simple_log):
        cert = crop_steering_certificate(
            data=simple_log,
            action_columns=["action"],
            scenario_column="scenario",
            outcome_column="outcome",
            mode="provable",
            iterations=1000,
            seed=42,
            discretize_actions=False,
            discretize_scenarios=False,
        )
        assert isinstance(cert, SteeringCertificate)
        assert cert.recommended_strategy in ["A", "B"]
        assert cert.certificate.mode == "provable"

    def test_full_certificate_with_weights(self, grow_log):
        cert = crop_steering_certificate(
            data=grow_log,
            action_columns=["ppfd", "irrigation_ml"],
            scenario_column="temperature",
            outcome_column="yield_g",
            quality_column="quality_score",
            cost_column="cost",
            risk_column="stress",
            payoff_weights={"outcome": 1.0, "quality": 0.5, "cost": 0.3, "risk": 0.5},
            mode="provable",
            iterations=1000,
            seed=42,
            n_action_bins=2,
            n_scenario_bins=2,
        )
        assert isinstance(cert, SteeringCertificate)
        assert cert.certificate.is_certified or cert.certificate.cce_gap >= 0

    def test_empirical_mode(self, simple_log):
        cert = crop_steering_certificate(
            data=simple_log,
            action_columns=["action"],
            scenario_column="scenario",
            outcome_column="outcome",
            mode="empirical",
            iterations=1000,
            tau=1.0,
            seed=42,
            discretize_actions=False,
            discretize_scenarios=False,
        )
        assert cert.certificate.mode == "empirical"

    def test_invalid_mode(self, simple_log):
        with pytest.raises(ValueError, match="mode"):
            crop_steering_certificate(
                data=simple_log,
                action_columns=["action"],
                scenario_column="scenario",
                outcome_column="outcome",
                mode="bogus",
                discretize_actions=False,
                discretize_scenarios=False,
            )

    def test_missing_column(self, simple_log):
        with pytest.raises(ValueError, match="Missing"):
            crop_steering_certificate(
                data=simple_log,
                action_columns=["nonexistent"],
                scenario_column="scenario",
                outcome_column="outcome",
            )

    def test_summary_renders(self, simple_log):
        cert = crop_steering_certificate(
            data=simple_log,
            action_columns=["action"],
            scenario_column="scenario",
            outcome_column="outcome",
            iterations=500,
            seed=42,
            discretize_actions=False,
            discretize_scenarios=False,
        )
        s = cert.summary()
        assert "CROP STEERING" in s
        assert "PAYOFF FORMULA" in s
        assert "RECOMMENDATION" in s
        assert "LIMITATIONS" in s
        assert "certified ε-CCE" in s.lower() or "ε-CCE" in s

    def test_phenogame_static_method(self, simple_log):
        cert = PhenoGame.crop_steering_certificate(
            data=simple_log,
            action_columns=["action"],
            scenario_column="scenario",
            outcome_column="outcome",
            iterations=500,
            seed=42,
            discretize_actions=False,
            discretize_scenarios=False,
        )
        assert isinstance(cert, SteeringCertificate)

    def test_fit_driver(self, grow_log):
        cert = crop_steering_certificate(
            data=grow_log,
            action_columns=["ppfd"],
            scenario_column="temperature",
            outcome_column="yield_g",
            iterations=500,
            seed=42,
            n_action_bins=2,
            n_scenario_bins=2,
            fit_driver_col="ppfd",
        )
        assert cert.fit_report is not None
        assert cert.fit_report.n_converged > 0

    def test_consensus_flag(self, simple_log):
        cert = crop_steering_certificate(
            data=simple_log,
            action_columns=["action"],
            scenario_column="scenario",
            outcome_column="outcome",
            iterations=500,
            seed=42,
            discretize_actions=False,
            discretize_scenarios=False,
        )
        assert isinstance(cert.consensus, bool)

    def test_csv_path_input(self, simple_log, tmp_path):
        csv_path = tmp_path / "test.csv"
        simple_log.to_csv(csv_path, index=False)
        cert = crop_steering_certificate(
            data=str(csv_path),
            action_columns=["action"],
            scenario_column="scenario",
            outcome_column="outcome",
            iterations=500,
            seed=42,
            discretize_actions=False,
            discretize_scenarios=False,
        )
        assert isinstance(cert, SteeringCertificate)
